### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by zannain** [Kubixrube/Jammming#1]
Hey Mario, it looks like your project isn't compiling. Once you are able to resolve this, reply to this thread and I'll review it. 

![image](https://user-images.githubusercontent.com/24375741/39558880-44965686-4e60-11e8-8513-0d2890fe3b4b.png)

**Comment by Kubixrube** [comment]
Ok its there now. Not sure where it went, It magically disappeared.

**Comment by zannain** [comment]
Thanks for fixing that, it looks like there is an issue with the redirect uri
![image](https://user-images.githubusercontent.com/24375741/39610886-64c69da0-4f21-11e8-8bd8-08ca8c0379e0.png)

**Comment by Kubixrube** [comment]
Hi zannain, thats because I posted it to surge. the redirect URI is set to that in the Spotify.js code. Right above it I commented out the localhost redirect. I can change it back if you need

**Comment by Kubixrube** [comment]
I changed it back to localhost
